package com.sunrise.boss.business.fee.persistent.wlincdecrdata;

// default package

import java.util.Date;


/**
 * WLIncDecrDataVO generated by MyEclipse - Hibernate Tools
 */

public class WLIncDecrDataVO  implements java.io.Serializable {


    // Fields    

     private Long logid;
     private Long incdecrid;
     private Long subsid;
     private Integer validbillcyc;
     private Long acctid;
     private Integer validflag;
     private Integer incdecrtype;
     private Date inputdate;
     private String oprcode;
     private Double incrdecramt;
     private String memo;
     private String attributeinfo;
     private String checkercode;
     private Integer outbillcyc;
     private Integer genbillcyc;
     private Integer award;
     private String incrdecrreason;
     private String lrsncode;
     private String srsncode;
     private Long isicp;
     private String icpid;
     private String icptype;
     private String lodge;
     private String portid;
     private String icptype2;
     private String modoprcode;
     private Integer oprtype;
     private Date oprtime;
     private Short busitype;
     private Short desputetype;

    // Constructors

    public Short getBusitype() {
		return busitype;
	}

	public void setBusitype(Short busitype) {
		this.busitype = busitype;
	}

	public Short getDesputetype() {
		return desputetype;
	}

	public void setDesputetype(Short desputetype) {
		this.desputetype = desputetype;
	}

	/** default constructor */
    public WLIncDecrDataVO() {
    }

	/** minimal constructor */
    public WLIncDecrDataVO(Integer validflag, Integer incdecrtype, Date inputdate, String oprcode) {
        this.validflag = validflag;
        this.incdecrtype = incdecrtype;
        this.inputdate = inputdate;
        this.oprcode = oprcode;
    }
    
    /** full constructor */
    public WLIncDecrDataVO(Long incdecrid, Long subsid, Integer validbillcyc, Long acctid, Integer validflag, Integer incdecrtype, Date inputdate, String oprcode, Double incrdecramt, String memo, String attributeinfo, String checkercode, Integer outbillcyc, Integer genbillcyc, Integer award, String incrdecrreason, String lrsncode, String srsncode, Long isicp, String icpid, String icptype, String lodge, String portid, String icptype2, String modoprcode, Integer oprtype, Date oprtime) {
        this.incdecrid = incdecrid;
        this.subsid = subsid;
        this.validbillcyc = validbillcyc;
        this.acctid = acctid;
        this.validflag = validflag;
        this.incdecrtype = incdecrtype;
        this.inputdate = inputdate;
        this.oprcode = oprcode;
        this.incrdecramt = incrdecramt;
        this.memo = memo;
        this.attributeinfo = attributeinfo;
        this.checkercode = checkercode;
        this.outbillcyc = outbillcyc;
        this.genbillcyc = genbillcyc;
        this.award = award;
        this.incrdecrreason = incrdecrreason;
        this.lrsncode = lrsncode;
        this.srsncode = srsncode;
        this.isicp = isicp;
        this.icpid = icpid;
        this.icptype = icptype;
        this.lodge = lodge;
        this.portid = portid;
        this.icptype2 = icptype2;
        this.modoprcode = modoprcode;
        this.oprtype = oprtype;
        this.oprtime = oprtime;
    }

   
    // Property accessors

    public Long getLogid() {
        return this.logid;
    }
    
    public void setLogid(Long logid) {
        this.logid = logid;
    }

    public Long getIncdecrid() {
        return this.incdecrid;
    }
    
    public void setIncdecrid(Long incdecrid) {
        this.incdecrid = incdecrid;
    }

    public Long getSubsid() {
        return this.subsid;
    }
    
    public void setSubsid(Long subsid) {
        this.subsid = subsid;
    }

    public Integer getValidbillcyc() {
        return this.validbillcyc;
    }
    
    public void setValidbillcyc(Integer validbillcyc) {
        this.validbillcyc = validbillcyc;
    }

    public Long getAcctid() {
        return this.acctid;
    }
    
    public void setAcctid(Long acctid) {
        this.acctid = acctid;
    }

    public Integer getValidflag() {
        return this.validflag;
    }
    
    public void setValidflag(Integer validflag) {
        this.validflag = validflag;
    }

    public Integer getIncdecrtype() {
        return this.incdecrtype;
    }
    
    public void setIncdecrtype(Integer incdecrtype) {
        this.incdecrtype = incdecrtype;
    }

    public Date getInputdate() {
        return this.inputdate;
    }
    
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    public String getOprcode() {
        return this.oprcode;
    }
    
    public void setOprcode(String oprcode) {
        this.oprcode = oprcode;
    }

    public Double getIncrdecramt() {
        return this.incrdecramt;
    }
    
    public void setIncrdecramt(Double incrdecramt) {
        this.incrdecramt = incrdecramt;
    }

    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getAttributeinfo() {
        return this.attributeinfo;
    }
    
    public void setAttributeinfo(String attributeinfo) {
        this.attributeinfo = attributeinfo;
    }

    public String getCheckercode() {
        return this.checkercode;
    }
    
    public void setCheckercode(String checkercode) {
        this.checkercode = checkercode;
    }

    public Integer getOutbillcyc() {
        return this.outbillcyc;
    }
    
    public void setOutbillcyc(Integer outbillcyc) {
        this.outbillcyc = outbillcyc;
    }

    public Integer getGenbillcyc() {
        return this.genbillcyc;
    }
    
    public void setGenbillcyc(Integer genbillcyc) {
        this.genbillcyc = genbillcyc;
    }

    public Integer getAward() {
        return this.award;
    }
    
    public void setAward(Integer award) {
        this.award = award;
    }

    public String getIncrdecrreason() {
        return this.incrdecrreason;
    }
    
    public void setIncrdecrreason(String incrdecrreason) {
        this.incrdecrreason = incrdecrreason;
    }

    public String getLrsncode() {
        return this.lrsncode;
    }
    
    public void setLrsncode(String lrsncode) {
        this.lrsncode = lrsncode;
    }

    public String getSrsncode() {
        return this.srsncode;
    }
    
    public void setSrsncode(String srsncode) {
        this.srsncode = srsncode;
    }

    public Long getIsicp() {
        return this.isicp;
    }
    
    public void setIsicp(Long isicp) {
        this.isicp = isicp;
    }

    public String getIcpid() {
        return this.icpid;
    }
    
    public void setIcpid(String icpid) {
        this.icpid = icpid;
    }

    public String getIcptype() {
        return this.icptype;
    }
    
    public void setIcptype(String icptype) {
        this.icptype = icptype;
    }

    public String getLodge() {
        return this.lodge;
    }
    
    public void setLodge(String lodge) {
        this.lodge = lodge;
    }

    public String getPortid() {
        return this.portid;
    }
    
    public void setPortid(String portid) {
        this.portid = portid;
    }

    public String getIcptype2() {
        return this.icptype2;
    }
    
    public void setIcptype2(String icptype2) {
        this.icptype2 = icptype2;
    }

    public String getModoprcode() {
        return this.modoprcode;
    }
    
    public void setModoprcode(String modoprcode) {
        this.modoprcode = modoprcode;
    }

    public Integer getOprtype() {
        return this.oprtype;
    }
    
    public void setOprtype(Integer oprtype) {
        this.oprtype = oprtype;
    }

    public Date getOprtime() {
        return this.oprtime;
    }
    
    public void setOprtime(Date oprtime) {
        this.oprtime = oprtime;
    }
   








}