
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.gmcc.pboss.pboss4crmservice;

import net.gmcc.pboss.domain.business.ServiceDispatcher;

/**
 * This class was generated by Apache CXF 2.3.8
 * 2012-02-09T15:21:29.968+08:00
 * Generated source version: 2.3.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "PBOSS4CRMService",
                      portName = "PBOSSServiceSoap",
                      targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/",
                      wsdlLocation = "/data/PBOSSWS1.02.wsdl",
                      //wsdlLocation = "classpath:wsdl/PBOSSWS1.02.wsdl",//file:wsdl/PBOSSWS1.02.wsdl
                      endpointInterface = "net.gmcc.pboss.pboss4crmservice.PBOSSServicePort")
                      
public class PBOSSServicePortImpl implements PBOSSServicePort {

    //private static final Logger LOG = Logger.getLogger(PBOSSServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see net.gmcc.pboss.pboss4crmservice.PBOSSServicePort#waysyn(net.gmcc.pboss.pboss4crmservice.Waysynreq  body )*
     */
    public net.gmcc.pboss.pboss4crmservice.Waysynrsp waysyn(Waysynreq body) { 
        //LOG.info("Executing operation waysyn");
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.pboss4crmservice.Waysynrsp _return = dispatcher.waysyn(body);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.gmcc.pboss.pboss4crmservice.PBOSSServicePort#returnorderin(net.gmcc.pboss.pboss4crmservice.Returnorderinreq  body )*
     */
    public net.gmcc.pboss.pboss4crmservice.Returnorderinrsp returnorderin(Returnorderinreq body) { 
        //LOG.info("Executing operation returnorderin");
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.pboss4crmservice.Returnorderinrsp _return = dispatcher.returnorderin(body);
            return _return;
            //return null;//异步接口，直接返回空
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.gmcc.pboss.pboss4crmservice.PBOSSServicePort#modifypromcomminfo(net.gmcc.pboss.pboss4crmservice.Modifypromcomminforeq  body )*
     */
    public net.gmcc.pboss.pboss4crmservice.Modifypromcomminforsp modifypromcomminfo(Modifypromcomminforeq body) { 
        //LOG.info("Executing operation modifypromcomminfo");
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.pboss4crmservice.Modifypromcomminforsp _return = dispatcher.modifypromcomminfo(body);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.gmcc.pboss.pboss4crmservice.PBOSSServicePort#empsyn(net.gmcc.pboss.pboss4crmservice.Empsynreq  body )*
     */
    public net.gmcc.pboss.pboss4crmservice.Empsynrsp empsyn(Empsynreq body) { 
        //LOG.info("Executing operation empsyn");
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.pboss4crmservice.Empsynrsp _return = dispatcher.empsyn(body);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.gmcc.pboss.pboss4crmservice.PBOSSServicePort#oprsyn(net.gmcc.pboss.pboss4crmservice.Oprsynreq  body )*
     */
    public net.gmcc.pboss.pboss4crmservice.Oprsynrsp oprsyn(Oprsynreq body) { 
        //LOG.info("Executing operation oprsyn");
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
        	net.gmcc.pboss.pboss4crmservice.Oprsynrsp _return = dispatcher.oprsyn(body);
          return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
