package net.gmcc.pboss.pboss4crmservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.8
 * 2012-02-09T15:21:30.078+08:00
 * Generated source version: 2.3.8
 * 
 */
@WebService(targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/", name = "PBOSSServicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PBOSSServicePort {

    /**
     * PBOSS_IM_009PBOSS渠道资料更新（全表字段同步）
     * 			
     */
    @WebResult(name = "waysynrsp", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/", partName = "body")
    @WebMethod(action = "http://www.gmcc.net/pboss/PBOSS4CRMService/waysyn")
    public Waysynrsp waysyn(
        @WebParam(partName = "body", name = "waysynreq", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/")
        Waysynreq body
    );

    /**
     * PBOSS_IM_011订单入帐/退入帐处理结果
     * 			
     */
    @WebResult(name = "returnorderinrsp", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/", partName = "body")
    @WebMethod(action = "http://www.gmcc.net/pboss/PBOSS4CRMService/returnorderin")
    public Returnorderinrsp returnorderin(
        @WebParam(partName = "body", name = "returnorderinreq", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/")
        Returnorderinreq body
    );

    /**
     * PBOSS_IM_010 新增注册推广专员信息
     * 			
     */
    @WebResult(name = "modifypromcomminforsp", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/", partName = "body")
    @WebMethod(action = "http://www.gmcc.net/pboss/PBOSS4CRMService/modifypromcomminfo")
    public Modifypromcomminforsp modifypromcomminfo(
        @WebParam(partName = "body", name = "modifypromcomminforeq", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/")
        Modifypromcomminforeq body
    );

    /**
     * PBOSS_IM_008人员资料更新
     * 			
     */
    @WebResult(name = "empsynrsp", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/", partName = "body")
    @WebMethod(action = "http://www.gmcc.net/pboss/PBOSS4CRMService/empsyn")
    public Empsynrsp empsyn(
        @WebParam(partName = "body", name = "empsynreq", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/")
        Empsynreq body
    );

    /**
     * PBOSS_IM_007工号资料更新
     * 			
     */
    @WebResult(name = "oprsynrsp", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/", partName = "body")
    @WebMethod(action = "http://www.gmcc.net/pboss/PBOSS4CRMService/oprsyn")
    public Oprsynrsp oprsyn(
        @WebParam(partName = "body", name = "oprsynreq", targetNamespace = "http://www.gmcc.net/pboss/PBOSS4CRMService/")
        Oprsynreq body
    );
}
