<%@ page  import="com.sunrise.jop.common.spring.SpringContextManager"%>
<%@ page  import="com.sunrise.jop.ui.component.ThemeSelector"%>
<%@ include file="/inc/head.inc" %>
<script type="text/javascript" src="<%= contextPath %>/js/pub/list.js"></script>

<s:i18n name="public">
<script type="text/javascript" language="javascript">
    var msgNoSelected="<s:text name="msgNoSelected"/>"
    var msgConfirmDelete="<s:text name="msgConfirmDelete"/>"
</script>
</s:i18n>
