package com.sunrise.boss.business.fee.billing.billinglog.persistent;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import com.sunrise.jop.infrastructure.db.BaseVO;

/**
 * IbWlBillinglog generated by MyEclipse - Hibernate Tools
 */

public class BillingLogVO extends BaseVO {

	// Fields

	private Long logid;

	private Long validbillcyc;

	private String billingcon;

	private Date starttime;

	private Date endtime;

	private String billingphase;

	private String subphase;

	private Long processcnt;

	private Double processamt;

	private String opercode;

	private String failreason;

	private Long status;

	private String batchnum;

	
	private Integer region;

	public Integer getRegion() {
		return region;
	}

	public void setRegion(Integer region) {
		this.region = region;
	}

	// Constructors

	/** default constructor */
	public BillingLogVO() {
	}

	/** minimal constructor */
	public BillingLogVO(Long logid, Long validbillcyc, String billingcon,
			String billingphase) {
		this.logid = logid;
		this.validbillcyc = validbillcyc;
		this.billingcon = billingcon;
		this.billingphase = billingphase;
	}

	/** full constructor */
	public BillingLogVO(Long logid, Long validbillcyc, String billingcon,
			Date starttime, Date endtime, String billingphase, String subphase,
			Long processcnt, Double processamt, String opercode,
			String failreason, Long status, String batchnum ) {
		this.logid = logid;
		this.validbillcyc = validbillcyc;
		this.billingcon = billingcon;
		this.starttime = starttime;
		this.endtime = endtime;
		this.billingphase = billingphase;
		this.subphase = subphase;
		this.processcnt = processcnt;
		this.processamt = processamt;
		this.opercode = opercode;
		this.failreason = failreason;
		this.status = status;
		this.batchnum = batchnum;
		 
	}

	// Property accessors

	public Long getLogid() {
		return this.logid;
	}

	public void setLogid(Long logid) {
		this.logid = logid;
	}

	public Long getValidbillcyc() {
		return this.validbillcyc;
	}

	public void setValidbillcyc(Long validbillcyc) {
		this.validbillcyc = validbillcyc;
	}

	public String getBillingcon() {
		return this.billingcon;
	}

	public void setBillingcon(String billingcon) {
		this.billingcon = billingcon;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getBillingphase() {
		return this.billingphase;
	}

	public void setBillingphase(String billingphase) {
		this.billingphase = billingphase;
	}

	public String getSubphase() {
		return this.subphase;
	}

	public void setSubphase(String subphase) {
		this.subphase = subphase;
	}

	public Long getProcesscnt() {
		return this.processcnt;
	}

	public void setProcesscnt(Long processcnt) {
		this.processcnt = processcnt;
	}

	public Double getProcessamt() {
		return this.processamt;
	}

	public void setProcessamt(Double processamt) {
		this.processamt = processamt;
	}

	public String getOpercode() {
		return this.opercode;
	}

	public void setOpercode(String opercode) {
		this.opercode = opercode;
	}

	public String getFailreason() {
		return this.failreason;
	}

	public void setFailreason(String failreason) {
		this.failreason = failreason;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getBatchnum() {
		return this.batchnum;
	}

	public void setBatchnum(String batchnum) {
		this.batchnum = batchnum;
	}

	 

	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (!(other instanceof BillingLogVO))
			return false;
		BillingLogVO castOther = (BillingLogVO) other;
		return new EqualsBuilder()
				.append(this.getLogid(), castOther.getLogid()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getLogid()).toHashCode();
	}

}