// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import com.sun.xml.rpc.encoding.SOAPInstanceBuilder;

public class AppResult_SOAPBuilder implements SOAPInstanceBuilder {
    private AppResult _instance;
    private java.lang.String message;
    private boolean successful;
    private static final int myMESSAGE_INDEX = 0;
    private static final int mySUCCESSFUL_INDEX = 1;
    
    public AppResult_SOAPBuilder() {
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
    
    public void setSuccessful(boolean successful) {
        this.successful = successful;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myMESSAGE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, Object memberValue) {
        switch(index) {
            case myMESSAGE_INDEX:
                _instance.setMessage((java.lang.String)memberValue);
                break;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(Object instance) {
        _instance = (AppResult)instance;
    }
    
    public Object getInstance() {
        return _instance;
    }
}
