// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class AppResult {
    private java.lang.String message;
    private boolean successful;
    
    public AppResult() {
    }
    
    public AppResult(java.lang.String message, boolean successful) {
        this.message = message;
        this.successful = successful;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
    
    public boolean isSuccessful() {
        return successful;
    }
    
    public void setSuccessful(boolean successful) {
        this.successful = successful;
    }
}
