// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class AuthResult {
    private java.lang.String idsTokenValue;
    private java.lang.String idsTokenName;
    private java.lang.String account;
    private boolean authResult;
    private java.lang.String authMsg;
    
    public AuthResult() {
    }
    
    public AuthResult(java.lang.String idsTokenValue, java.lang.String idsTokenName, java.lang.String account, boolean authResult, java.lang.String authMsg) {
        this.idsTokenValue = idsTokenValue;
        this.idsTokenName = idsTokenName;
        this.account = account;
        this.authResult = authResult;
        this.authMsg = authMsg;
    }
    
    public java.lang.String getIdsTokenValue() {
        return idsTokenValue;
    }
    
    public void setIdsTokenValue(java.lang.String idsTokenValue) {
        this.idsTokenValue = idsTokenValue;
    }
    
    public java.lang.String getIdsTokenName() {
        return idsTokenName;
    }
    
    public void setIdsTokenName(java.lang.String idsTokenName) {
        this.idsTokenName = idsTokenName;
    }
    
    public java.lang.String getAccount() {
        return account;
    }
    
    public void setAccount(java.lang.String account) {
        this.account = account;
    }
    
    public boolean isAuthResult() {
        return authResult;
    }
    
    public void setAuthResult(boolean authResult) {
        this.authResult = authResult;
    }
    
    public java.lang.String getAuthMsg() {
        return authMsg;
    }
    
    public void setAuthMsg(java.lang.String authMsg) {
        this.authMsg = authMsg;
    }
}
