// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import com.sun.xml.rpc.encoding.SOAPInstanceBuilder;

public class AuthResult_SOAPBuilder implements SOAPInstanceBuilder {
    private AuthResult _instance;
    private java.lang.String idsTokenValue;
    private java.lang.String idsTokenName;
    private java.lang.String account;
    private boolean authResult;
    private java.lang.String authMsg;
    private static final int myIDSTOKENVALUE_INDEX = 0;
    private static final int myIDSTOKENNAME_INDEX = 1;
    private static final int myACCOUNT_INDEX = 2;
    private static final int myAUTHRESULT_INDEX = 3;
    private static final int myAUTHMSG_INDEX = 4;
    
    public AuthResult_SOAPBuilder() {
    }
    
    public void setIdsTokenValue(java.lang.String idsTokenValue) {
        this.idsTokenValue = idsTokenValue;
    }
    
    public void setIdsTokenName(java.lang.String idsTokenName) {
        this.idsTokenName = idsTokenName;
    }
    
    public void setAccount(java.lang.String account) {
        this.account = account;
    }
    
    public void setAuthResult(boolean authResult) {
        this.authResult = authResult;
    }
    
    public void setAuthMsg(java.lang.String authMsg) {
        this.authMsg = authMsg;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myIDSTOKENVALUE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myIDSTOKENNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myACCOUNT_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myAUTHMSG_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, Object memberValue) {
        switch(index) {
            case myIDSTOKENVALUE_INDEX:
                _instance.setIdsTokenValue((java.lang.String)memberValue);
                break;
            case myIDSTOKENNAME_INDEX:
                _instance.setIdsTokenName((java.lang.String)memberValue);
                break;
            case myACCOUNT_INDEX:
                _instance.setAccount((java.lang.String)memberValue);
                break;
            case myAUTHMSG_INDEX:
                _instance.setAuthMsg((java.lang.String)memberValue);
                break;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(Object instance) {
        _instance = (AuthResult)instance;
    }
    
    public Object getInstance() {
        return _instance;
    }
}
