// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class OrganizationInfo_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final QName ns1_queryResult_QNAME = new QName("", "queryResult");
    private static final QName ns2_int_TYPE_QNAME = SchemaConstants.QNAME_TYPE_INT;
    private CombinedSerializer myns2__int__int_Int_Serializer;
    private static final QName ns1_orgInfo_QNAME = new QName("", "orgInfo");
    private static final QName ns3_ArrayOfOrgDetail_TYPE_QNAME = new QName("http://portal.gmcc.net/types/UIPService", "ArrayOfOrgDetail");
    private CombinedSerializer myns3_ArrayOfOrgDetail__OrgDetailArray_SOAPSerializer1;
    private static final int myQUERYRESULT_INDEX = 0;
    private static final int myORGINFO_INDEX = 1;
    
    public OrganizationInfo_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns2__int__int_Int_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, int.class, ns2_int_TYPE_QNAME);
        myns3_ArrayOfOrgDetail__OrgDetailArray_SOAPSerializer1 = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.skywin.webserviceclients.uip.OrgDetail[].class, ns3_ArrayOfOrgDetail_TYPE_QNAME);
    }
    
    public Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        OrganizationInfo instance = new OrganizationInfo();
        OrganizationInfo_SOAPBuilder builder = null;
        Object member;
        boolean isComplete = true;
        QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_queryResult_QNAME)) {
                member = myns2__int__int_Int_Serializer.deserialize(ns1_queryResult_QNAME, reader, context);
                instance.setQueryResult(((Integer)member).intValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_orgInfo_QNAME)) {
                member = myns3_ArrayOfOrgDetail__OrgDetailArray_SOAPSerializer1.deserialize(ns1_orgInfo_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new OrganizationInfo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myORGINFO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setOrgInfo((com.skywin.webserviceclients.uip.OrgDetail[])member);
                }
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (Object)instance : (Object)state);
    }
    
    public void doSerializeInstance(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.skywin.webserviceclients.uip.OrganizationInfo instance = (com.skywin.webserviceclients.uip.OrganizationInfo)obj;
        
        myns2__int__int_Int_Serializer.serialize(new Integer(instance.getQueryResult()), ns1_queryResult_QNAME, null, writer, context);
        myns3_ArrayOfOrgDetail__OrgDetailArray_SOAPSerializer1.serialize(instance.getOrgInfo(), ns1_orgInfo_QNAME, null, writer, context);
    }
}
