// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import com.sun.xml.rpc.encoding.*;
import java.lang.IllegalArgumentException;

public class OrganizationInfo_SOAPBuilder implements SOAPInstanceBuilder {
    private OrganizationInfo _instance;
    private int queryResult;
    private com.skywin.webserviceclients.uip.OrgDetail[] orgInfo;
    private static final int myQUERYRESULT_INDEX = 0;
    private static final int myORGINFO_INDEX = 1;
    
    public OrganizationInfo_SOAPBuilder() {
    }
    
    public void setQueryResult(int queryResult) {
        this.queryResult = queryResult;
    }
    
    public void setOrgInfo(com.skywin.webserviceclients.uip.OrgDetail[] orgInfo) {
        this.orgInfo = orgInfo;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myORGINFO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, Object memberValue) {
        switch(index) {
            case myORGINFO_INDEX:
                _instance.setOrgInfo((com.skywin.webserviceclients.uip.OrgDetail[])memberValue);
                break;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(Object instance) {
        _instance = (OrganizationInfo)instance;
    }
    
    public Object getInstance() {
        return _instance;
    }
}
