// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import javax.xml.namespace.QName;

import com.sun.xml.rpc.encoding.CombinedSerializer;
import com.sun.xml.rpc.encoding.Initializable;
import com.sun.xml.rpc.encoding.InternalTypeMappingRegistry;
import com.sun.xml.rpc.encoding.ObjectSerializerBase;
import com.sun.xml.rpc.encoding.SOAPDeserializationContext;
import com.sun.xml.rpc.encoding.SOAPDeserializationState;
import com.sun.xml.rpc.encoding.SOAPSerializationContext;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.streaming.XMLReader;
import com.sun.xml.rpc.streaming.XMLReaderUtil;
import com.sun.xml.rpc.streaming.XMLWriter;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;

public class OrgDetail_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final QName ns1_OULevel_QNAME = new QName("", "OULevel");
    private static final QName ns2_int_TYPE_QNAME = SchemaConstants.QNAME_TYPE_INT;
    private CombinedSerializer myns2__int__int_Int_Serializer;
    private static final QName ns1_organizationName_QNAME = new QName("", "organizationName");
    private static final QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer myns2_string__java_lang_String_String_Serializer;
    private static final QName ns1_OUOrder_QNAME = new QName("", "OUOrder");
    private static final QName ns1_parentOUID_QNAME = new QName("", "parentOUID");
    private static final QName ns1_OUID_QNAME = new QName("", "OUID");
    private static final QName ns1_OUFullName_QNAME = new QName("", "OUFullName");
    private static final QName ns1_orgDN_QNAME = new QName("", "orgDN");
    private static final int myOULEVEL_INDEX = 0;
    private static final int myORGANIZATIONNAME_INDEX = 1;
    private static final int myOUORDER_INDEX = 2;
    private static final int myPARENTOUID_INDEX = 3;
    private static final int myOUID_INDEX = 4;
    private static final int myOUFULLNAME_INDEX = 5;
    private static final int myORGDN_INDEX = 6;
    
    public OrgDetail_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns2__int__int_Int_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, int.class, ns2_int_TYPE_QNAME);
        myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns2_string_TYPE_QNAME);
    }
    
    public Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        OrgDetail instance = new OrgDetail();
        OrgDetail_SOAPBuilder builder = null;
        Object member;
        boolean isComplete = true;
        QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_OULevel_QNAME)) {
                member = myns2__int__int_Int_Serializer.deserialize(ns1_OULevel_QNAME, reader, context);
                instance.setOULevel(((Integer)member).intValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_organizationName_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_organizationName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new OrgDetail_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myORGANIZATIONNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setOrganizationName((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_OUOrder_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_OUOrder_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new OrgDetail_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myOUORDER_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setOUOrder((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_parentOUID_QNAME)) {
                member = myns2__int__int_Int_Serializer.deserialize(ns1_parentOUID_QNAME, reader, context);
                instance.setParentOUID(((Integer)member).intValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_OUID_QNAME)) {
                member = myns2__int__int_Int_Serializer.deserialize(ns1_OUID_QNAME, reader, context);
                instance.setOUID(((Integer)member).intValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_OUFullName_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_OUFullName_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new OrgDetail_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myOUFULLNAME_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setOUFullName((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_orgDN_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_orgDN_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new OrgDetail_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myORGDN_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setOrgDN((java.lang.String)member);
                }
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (Object)instance : (Object)state);
    }
    
    public void doSerializeInstance(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.skywin.webserviceclients.uip.OrgDetail instance = (com.skywin.webserviceclients.uip.OrgDetail)obj;
        
        myns2__int__int_Int_Serializer.serialize(new Integer(instance.getOULevel()), ns1_OULevel_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getOrganizationName(), ns1_organizationName_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getOUOrder(), ns1_OUOrder_QNAME, null, writer, context);
        myns2__int__int_Int_Serializer.serialize(new Integer(instance.getParentOUID()), ns1_parentOUID_QNAME, null, writer, context);
        myns2__int__int_Int_Serializer.serialize(new Integer(instance.getOUID()), ns1_OUID_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getOUFullName(), ns1_OUFullName_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getOrgDN(), ns1_orgDN_QNAME, null, writer, context);
    }
}
