// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import com.sun.xml.rpc.encoding.*;
import java.lang.IllegalArgumentException;

public class OrgDetail_SOAPBuilder implements SOAPInstanceBuilder {
    private OrgDetail _instance;
    private int OULevel;
    private java.lang.String organizationName;
    private java.lang.String OUOrder;
    private int parentOUID;
    private int OUID;
    private java.lang.String OUFullName;
    private java.lang.String orgDN;
    private static final int myOULEVEL_INDEX = 0;
    private static final int myORGANIZATIONNAME_INDEX = 1;
    private static final int myOUORDER_INDEX = 2;
    private static final int myPARENTOUID_INDEX = 3;
    private static final int myOUID_INDEX = 4;
    private static final int myOUFULLNAME_INDEX = 5;
    private static final int myORGDN_INDEX = 6;
    
    public OrgDetail_SOAPBuilder() {
    }
    
    public void setOULevel(int OULevel) {
        this.OULevel = OULevel;
    }
    
    public void setOrganizationName(java.lang.String organizationName) {
        this.organizationName = organizationName;
    }
    
    public void setOUOrder(java.lang.String OUOrder) {
        this.OUOrder = OUOrder;
    }
    
    public void setParentOUID(int parentOUID) {
        this.parentOUID = parentOUID;
    }
    
    public void setOUID(int OUID) {
        this.OUID = OUID;
    }
    
    public void setOUFullName(java.lang.String OUFullName) {
        this.OUFullName = OUFullName;
    }
    
    public void setOrgDN(java.lang.String orgDN) {
        this.orgDN = orgDN;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myORGANIZATIONNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myOUORDER_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myOUFULLNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myORGDN_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, Object memberValue) {
        switch(index) {
            case myORGANIZATIONNAME_INDEX:
                _instance.setOrganizationName((java.lang.String)memberValue);
                break;
            case myOUORDER_INDEX:
                _instance.setOUOrder((java.lang.String)memberValue);
                break;
            case myOUFULLNAME_INDEX:
                _instance.setOUFullName((java.lang.String)memberValue);
                break;
            case myORGDN_INDEX:
                _instance.setOrgDN((java.lang.String)memberValue);
                break;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(Object instance) {
        _instance = (OrgDetail)instance;
    }
    
    public Object getInstance() {
        return _instance;
    }
}
