// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class OrgDetail {
    private int OULevel;
    private java.lang.String organizationName;
    private java.lang.String OUOrder;
    private int parentOUID;
    private int OUID;
    private java.lang.String OUFullName;
    private java.lang.String orgDN;
    
    public OrgDetail() {
    }
    
    public OrgDetail(int OULevel, java.lang.String organizationName, java.lang.String OUOrder, int parentOUID, int OUID, java.lang.String OUFullName, java.lang.String orgDN) {
        this.OULevel = OULevel;
        this.organizationName = organizationName;
        this.OUOrder = OUOrder;
        this.parentOUID = parentOUID;
        this.OUID = OUID;
        this.OUFullName = OUFullName;
        this.orgDN = orgDN;
    }
    
    public int getOULevel() {
        return OULevel;
    }
    
    public void setOULevel(int OULevel) {
        this.OULevel = OULevel;
    }
    
    public java.lang.String getOrganizationName() {
        return organizationName;
    }
    
    public void setOrganizationName(java.lang.String organizationName) {
        this.organizationName = organizationName;
    }
    
    public java.lang.String getOUOrder() {
        return OUOrder;
    }
    
    public void setOUOrder(java.lang.String OUOrder) {
        this.OUOrder = OUOrder;
    }
    
    public int getParentOUID() {
        return parentOUID;
    }
    
    public void setParentOUID(int parentOUID) {
        this.parentOUID = parentOUID;
    }
    
    public int getOUID() {
        return OUID;
    }
    
    public void setOUID(int OUID) {
        this.OUID = OUID;
    }
    
    public java.lang.String getOUFullName() {
        return OUFullName;
    }
    
    public void setOUFullName(java.lang.String OUFullName) {
        this.OUFullName = OUFullName;
    }
    
    public java.lang.String getOrgDN() {
        return orgDN;
    }
    
    public void setOrgDN(java.lang.String orgDN) {
        this.orgDN = orgDN;
    }
}
