// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import javax.xml.namespace.QName;

import com.sun.xml.rpc.encoding.CombinedSerializer;
import com.sun.xml.rpc.encoding.Initializable;
import com.sun.xml.rpc.encoding.InternalTypeMappingRegistry;
import com.sun.xml.rpc.encoding.ObjectSerializerBase;
import com.sun.xml.rpc.encoding.SOAPDeserializationContext;
import com.sun.xml.rpc.encoding.SOAPDeserializationState;
import com.sun.xml.rpc.encoding.SOAPSerializationContext;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.streaming.XMLReader;
import com.sun.xml.rpc.streaming.XMLReaderUtil;
import com.sun.xml.rpc.streaming.XMLWriter;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;

public class QueryResult_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final QName ns1_queryResult_QNAME = new QName("", "queryResult");
    private static final QName ns2_int_TYPE_QNAME = SchemaConstants.QNAME_TYPE_INT;
    private CombinedSerializer myns2__int__int_Int_Serializer;
    private static final QName ns1_userInfo_QNAME = new QName("", "userInfo");
    private static final QName ns3_ArrayOfUserInfo_TYPE_QNAME = new QName("http://portal.gmcc.net/types/UIPService", "ArrayOfUserInfo");
    private CombinedSerializer myns3_ArrayOfUserInfo__UserInfoArray_SOAPSerializer1;
    private static final int myQUERYRESULT_INDEX = 0;
    private static final int myUSERINFO_INDEX = 1;
    
    public QueryResult_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns2__int__int_Int_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, int.class, ns2_int_TYPE_QNAME);
        myns3_ArrayOfUserInfo__UserInfoArray_SOAPSerializer1 = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.skywin.webserviceclients.uip.UserInfo[].class, ns3_ArrayOfUserInfo_TYPE_QNAME);
    }
    
    public Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        QueryResult instance = new QueryResult();
        QueryResult_SOAPBuilder builder = null;
        Object member;
        boolean isComplete = true;
        QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_queryResult_QNAME)) {
                member = myns2__int__int_Int_Serializer.deserialize(ns1_queryResult_QNAME, reader, context);
                instance.setQueryResult(((Integer)member).intValue());
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_userInfo_QNAME)) {
                member = myns3_ArrayOfUserInfo__UserInfoArray_SOAPSerializer1.deserialize(ns1_userInfo_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new QueryResult_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myUSERINFO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setUserInfo((com.skywin.webserviceclients.uip.UserInfo[])member);
                }
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (Object)instance : (Object)state);
    }
    
    public void doSerializeInstance(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.skywin.webserviceclients.uip.QueryResult instance = (com.skywin.webserviceclients.uip.QueryResult)obj;
        
        myns2__int__int_Int_Serializer.serialize(new Integer(instance.getQueryResult()), ns1_queryResult_QNAME, null, writer, context);
        myns3_ArrayOfUserInfo__UserInfoArray_SOAPSerializer1.serialize(instance.getUserInfo(), ns1_userInfo_QNAME, null, writer, context);
    }
}
