// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import com.sun.xml.rpc.encoding.SOAPInstanceBuilder;

public class QueryResult_SOAPBuilder implements SOAPInstanceBuilder {
    private QueryResult _instance;
    private int queryResult;
    private com.skywin.webserviceclients.uip.UserInfo[] userInfo;
    private static final int myQUERYRESULT_INDEX = 0;
    private static final int myUSERINFO_INDEX = 1;
    
    public QueryResult_SOAPBuilder() {
    }
    
    public void setQueryResult(int queryResult) {
        this.queryResult = queryResult;
    }
    
    public void setUserInfo(com.skywin.webserviceclients.uip.UserInfo[] userInfo) {
        this.userInfo = userInfo;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myUSERINFO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, Object memberValue) {
        switch(index) {
            case myUSERINFO_INDEX:
                _instance.setUserInfo((com.skywin.webserviceclients.uip.UserInfo[])memberValue);
                break;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(Object instance) {
        _instance = (QueryResult)instance;
    }
    
    public Object getInstance() {
        return _instance;
    }
}
