// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class QueryResult {
    private int queryResult;
    private com.skywin.webserviceclients.uip.UserInfo[] userInfo;
    
    public QueryResult() {
    }
    
    public QueryResult(int queryResult, com.skywin.webserviceclients.uip.UserInfo[] userInfo) {
        this.queryResult = queryResult;
        this.userInfo = userInfo;
    }
    
    public int getQueryResult() {
        return queryResult;
    }
    
    public void setQueryResult(int queryResult) {
        this.queryResult = queryResult;
    }
    
    public com.skywin.webserviceclients.uip.UserInfo[] getUserInfo() {
        return userInfo;
    }
    
    public void setUserInfo(com.skywin.webserviceclients.uip.UserInfo[] userInfo) {
        this.userInfo = userInfo;
    }
}
