// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_applicationToDo_RequestStruct {
    private java.lang.String string_1;
    private java.lang.String string_2;
    private java.lang.String string_3;
    private java.lang.String string_4;
    private java.lang.String string_5;
    private int int_6;
    private java.lang.String string_7;
    private java.lang.String string_8;
    private java.lang.String string_9;
    private java.lang.String string_10;
    private int int_11;
    
    public UIPServiceIF_applicationToDo_RequestStruct() {
    }
    
    public UIPServiceIF_applicationToDo_RequestStruct(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, java.lang.String string_4, java.lang.String string_5, int int_6, java.lang.String string_7, java.lang.String string_8, java.lang.String string_9, java.lang.String string_10, int int_11) {
        this.string_1 = string_1;
        this.string_2 = string_2;
        this.string_3 = string_3;
        this.string_4 = string_4;
        this.string_5 = string_5;
        this.int_6 = int_6;
        this.string_7 = string_7;
        this.string_8 = string_8;
        this.string_9 = string_9;
        this.string_10 = string_10;
        this.int_11 = int_11;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_2() {
        return string_2;
    }
    
    public void setString_2(java.lang.String string_2) {
        this.string_2 = string_2;
    }
    
    public java.lang.String getString_3() {
        return string_3;
    }
    
    public void setString_3(java.lang.String string_3) {
        this.string_3 = string_3;
    }
    
    public java.lang.String getString_4() {
        return string_4;
    }
    
    public void setString_4(java.lang.String string_4) {
        this.string_4 = string_4;
    }
    
    public java.lang.String getString_5() {
        return string_5;
    }
    
    public void setString_5(java.lang.String string_5) {
        this.string_5 = string_5;
    }
    
    public int getInt_6() {
        return int_6;
    }
    
    public void setInt_6(int int_6) {
        this.int_6 = int_6;
    }
    
    public java.lang.String getString_7() {
        return string_7;
    }
    
    public void setString_7(java.lang.String string_7) {
        this.string_7 = string_7;
    }
    
    public java.lang.String getString_8() {
        return string_8;
    }
    
    public void setString_8(java.lang.String string_8) {
        this.string_8 = string_8;
    }
    
    public java.lang.String getString_9() {
        return string_9;
    }
    
    public void setString_9(java.lang.String string_9) {
        this.string_9 = string_9;
    }
    
    public java.lang.String getString_10() {
        return string_10;
    }
    
    public void setString_10(java.lang.String string_10) {
        this.string_10 = string_10;
    }
    
    public int getInt_11() {
        return int_11;
    }
    
    public void setInt_11(int int_11) {
        this.int_11 = int_11;
    }
}
