// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_getVersion_RequestStruct {
    
    public UIPServiceIF_getVersion_RequestStruct() {
    }
}
