// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import javax.xml.namespace.QName;

import com.sun.xml.rpc.encoding.CombinedSerializer;
import com.sun.xml.rpc.encoding.DeserializationException;
import com.sun.xml.rpc.encoding.Initializable;
import com.sun.xml.rpc.encoding.InternalTypeMappingRegistry;
import com.sun.xml.rpc.encoding.ObjectSerializerBase;
import com.sun.xml.rpc.encoding.SOAPDeserializationContext;
import com.sun.xml.rpc.encoding.SOAPDeserializationState;
import com.sun.xml.rpc.encoding.SOAPSerializationContext;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.streaming.XMLReader;
import com.sun.xml.rpc.streaming.XMLReaderUtil;
import com.sun.xml.rpc.streaming.XMLWriter;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;

public class UIPServiceIF_applicationToRead_RequestStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final QName ns1_String_1_QNAME = new QName("", "String_1");
    private static final QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer myns2_string__java_lang_String_String_Serializer;
    private static final QName ns1_String_2_QNAME = new QName("", "String_2");
    private static final QName ns1_String_3_QNAME = new QName("", "String_3");
    private static final QName ns1_String_4_QNAME = new QName("", "String_4");
    private static final QName ns1_int_5_QNAME = new QName("", "int_5");
    private static final QName ns2_int_TYPE_QNAME = SchemaConstants.QNAME_TYPE_INT;
    private CombinedSerializer myns2__int__int_Int_Serializer;
    private static final QName ns1_String_6_QNAME = new QName("", "String_6");
    private static final QName ns1_String_7_QNAME = new QName("", "String_7");
    private static final QName ns1_String_8_QNAME = new QName("", "String_8");
    private static final QName ns1_String_9_QNAME = new QName("", "String_9");
    private static final QName ns1_int_10_QNAME = new QName("", "int_10");
    private static final int mySTRING_1_INDEX = 0;
    private static final int mySTRING_2_INDEX = 1;
    private static final int mySTRING_3_INDEX = 2;
    private static final int mySTRING_4_INDEX = 3;
    private static final int myINT_5_INDEX = 4;
    private static final int mySTRING_6_INDEX = 5;
    private static final int mySTRING_7_INDEX = 6;
    private static final int mySTRING_8_INDEX = 7;
    private static final int mySTRING_9_INDEX = 8;
    private static final int myINT_10_INDEX = 9;
    
    public UIPServiceIF_applicationToRead_RequestStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns2_string_TYPE_QNAME);
        myns2__int__int_Int_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, int.class, ns2_int_TYPE_QNAME);
    }
    
    public Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        UIPServiceIF_applicationToRead_RequestStruct instance = new UIPServiceIF_applicationToRead_RequestStruct();
        UIPServiceIF_applicationToRead_RequestStruct_SOAPBuilder builder = null;
        Object member;
        boolean isComplete = true;
        QName elementName;
        
        reader.nextElementContent();
        for (int i=0; i<10; i++) {
            elementName = reader.getName();
            if (reader.getState() == XMLReader.END) {
                break;
            }
            if (elementName.equals(ns1_String_1_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_1_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_applicationToRead_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_1_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_1((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_String_2_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_2_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_applicationToRead_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_2_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_2((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_String_3_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_3_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_applicationToRead_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_3_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_3((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_String_4_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_4_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_applicationToRead_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_4_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_4((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_int_5_QNAME)) {
                member = myns2__int__int_Int_Serializer.deserialize(ns1_int_5_QNAME, reader, context);
                instance.setInt_5(((Integer)member).intValue());
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_String_6_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_6_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_applicationToRead_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_6_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_6((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_String_7_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_7_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_applicationToRead_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_7_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_7((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_String_8_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_8_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_applicationToRead_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_8_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_8((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_String_9_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_9_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_applicationToRead_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_9_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_9((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_int_10_QNAME)) {
                member = myns2__int__int_Int_Serializer.deserialize(ns1_int_10_QNAME, reader, context);
                instance.setInt_10(((Integer)member).intValue());
                reader.nextElementContent();
                continue;
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_int_10_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (Object)instance : (Object)state);
    }
    
    public void doSerializeInstance(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.skywin.webserviceclients.uip.UIPServiceIF_applicationToRead_RequestStruct instance = (com.skywin.webserviceclients.uip.UIPServiceIF_applicationToRead_RequestStruct)obj;
        
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_1(), ns1_String_1_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_2(), ns1_String_2_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_3(), ns1_String_3_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_4(), ns1_String_4_QNAME, null, writer, context);
        myns2__int__int_Int_Serializer.serialize(new Integer(instance.getInt_5()), ns1_int_5_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_6(), ns1_String_6_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_7(), ns1_String_7_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_8(), ns1_String_8_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_9(), ns1_String_9_QNAME, null, writer, context);
        myns2__int__int_Int_Serializer.serialize(new Integer(instance.getInt_10()), ns1_int_10_QNAME, null, writer, context);
    }
}
