// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import com.sun.xml.rpc.encoding.SOAPInstanceBuilder;

public class UIPServiceIF_applicationToDo_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private UIPServiceIF_applicationToDo_RequestStruct _instance;
    private java.lang.String string_1;
    private java.lang.String string_2;
    private java.lang.String string_3;
    private java.lang.String string_4;
    private java.lang.String string_5;
    private int int_6;
    private java.lang.String string_7;
    private java.lang.String string_8;
    private java.lang.String string_9;
    private java.lang.String string_10;
    private int int_11;
    private static final int mySTRING_1_INDEX = 0;
    private static final int mySTRING_2_INDEX = 1;
    private static final int mySTRING_3_INDEX = 2;
    private static final int mySTRING_4_INDEX = 3;
    private static final int mySTRING_5_INDEX = 4;
    private static final int myINT_6_INDEX = 5;
    private static final int mySTRING_7_INDEX = 6;
    private static final int mySTRING_8_INDEX = 7;
    private static final int mySTRING_9_INDEX = 8;
    private static final int mySTRING_10_INDEX = 9;
    private static final int myINT_11_INDEX = 10;
    
    public UIPServiceIF_applicationToDo_RequestStruct_SOAPBuilder() {
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public void setString_2(java.lang.String string_2) {
        this.string_2 = string_2;
    }
    
    public void setString_3(java.lang.String string_3) {
        this.string_3 = string_3;
    }
    
    public void setString_4(java.lang.String string_4) {
        this.string_4 = string_4;
    }
    
    public void setString_5(java.lang.String string_5) {
        this.string_5 = string_5;
    }
    
    public void setInt_6(int int_6) {
        this.int_6 = int_6;
    }
    
    public void setString_7(java.lang.String string_7) {
        this.string_7 = string_7;
    }
    
    public void setString_8(java.lang.String string_8) {
        this.string_8 = string_8;
    }
    
    public void setString_9(java.lang.String string_9) {
        this.string_9 = string_9;
    }
    
    public void setString_10(java.lang.String string_10) {
        this.string_10 = string_10;
    }
    
    public void setInt_11(int int_11) {
        this.int_11 = int_11;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case mySTRING_1_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTRING_2_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTRING_3_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTRING_4_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTRING_5_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTRING_7_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTRING_8_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTRING_9_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySTRING_10_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, Object memberValue) {
        switch(index) {
            case mySTRING_1_INDEX:
                _instance.setString_1((java.lang.String)memberValue);
                break;
            case mySTRING_2_INDEX:
                _instance.setString_2((java.lang.String)memberValue);
                break;
            case mySTRING_3_INDEX:
                _instance.setString_3((java.lang.String)memberValue);
                break;
            case mySTRING_4_INDEX:
                _instance.setString_4((java.lang.String)memberValue);
                break;
            case mySTRING_5_INDEX:
                _instance.setString_5((java.lang.String)memberValue);
                break;
            case mySTRING_7_INDEX:
                _instance.setString_7((java.lang.String)memberValue);
                break;
            case mySTRING_8_INDEX:
                _instance.setString_8((java.lang.String)memberValue);
                break;
            case mySTRING_9_INDEX:
                _instance.setString_9((java.lang.String)memberValue);
                break;
            case mySTRING_10_INDEX:
                _instance.setString_10((java.lang.String)memberValue);
                break;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(Object instance) {
        _instance = (UIPServiceIF_applicationToDo_RequestStruct)instance;
    }
    
    public Object getInstance() {
        return _instance;
    }
}
