// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import javax.xml.namespace.QName;

import com.sun.xml.rpc.encoding.CombinedSerializer;
import com.sun.xml.rpc.encoding.DeserializationException;
import com.sun.xml.rpc.encoding.Initializable;
import com.sun.xml.rpc.encoding.InternalTypeMappingRegistry;
import com.sun.xml.rpc.encoding.ObjectSerializerBase;
import com.sun.xml.rpc.encoding.SOAPDeserializationContext;
import com.sun.xml.rpc.encoding.SOAPDeserializationState;
import com.sun.xml.rpc.encoding.SOAPSerializationContext;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.streaming.XMLReader;
import com.sun.xml.rpc.streaming.XMLReaderUtil;
import com.sun.xml.rpc.streaming.XMLWriter;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;

public class UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final QName ns1_int_1_QNAME = new QName("", "int_1");
    private static final QName ns2_int_TYPE_QNAME = SchemaConstants.QNAME_TYPE_INT;
    private CombinedSerializer myns2__int__int_Int_Serializer;
    private static final QName ns1_boolean_2_QNAME = new QName("", "boolean_2");
    private static final QName ns2_boolean_TYPE_QNAME = SchemaConstants.QNAME_TYPE_BOOLEAN;
    private CombinedSerializer myns2__boolean__boolean_Boolean_Serializer;
    private static final QName ns1_String_3_QNAME = new QName("", "String_3");
    private static final QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer myns2_string__java_lang_String_String_Serializer;
    private static final QName ns1_String_4_QNAME = new QName("", "String_4");
    private static final int myINT_1_INDEX = 0;
    private static final int myBOOLEAN_2_INDEX = 1;
    private static final int mySTRING_3_INDEX = 2;
    private static final int mySTRING_4_INDEX = 3;
    
    public UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        myns2__int__int_Int_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, int.class, ns2_int_TYPE_QNAME);
        myns2__boolean__boolean_Boolean_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, boolean.class, ns2_boolean_TYPE_QNAME);
        myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns2_string_TYPE_QNAME);
    }
    
    public Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct instance = new UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct();
        UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct_SOAPBuilder builder = null;
        Object member;
        boolean isComplete = true;
        QName elementName;
        
        reader.nextElementContent();
        for (int i=0; i<4; i++) {
            elementName = reader.getName();
            if (reader.getState() == XMLReader.END) {
                break;
            }
            if (elementName.equals(ns1_int_1_QNAME)) {
                member = myns2__int__int_Int_Serializer.deserialize(ns1_int_1_QNAME, reader, context);
                instance.setInt_1(((Integer)member).intValue());
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_boolean_2_QNAME)) {
                member = myns2__boolean__boolean_Boolean_Serializer.deserialize(ns1_boolean_2_QNAME, reader, context);
                instance.setBoolean_2(((Boolean)member).booleanValue());
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_String_3_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_3_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_3_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_3((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_String_4_QNAME)) {
                member = myns2_string__java_lang_String_String_Serializer.deserialize(ns1_String_4_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySTRING_4_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setString_4((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_String_4_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (Object)instance : (Object)state);
    }
    
    public void doSerializeInstance(Object obj, XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.skywin.webserviceclients.uip.UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct instance = (com.skywin.webserviceclients.uip.UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct)obj;
        
        myns2__int__int_Int_Serializer.serialize(new Integer(instance.getInt_1()), ns1_int_1_QNAME, null, writer, context);
        myns2__boolean__boolean_Boolean_Serializer.serialize(new Boolean(instance.isBoolean_2()), ns1_boolean_2_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_3(), ns1_String_3_QNAME, null, writer, context);
        myns2_string__java_lang_String_String_Serializer.serialize(instance.getString_4(), ns1_String_4_QNAME, null, writer, context);
    }
}
