// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_Logout_ResponseStruct {
    
    public UIPServiceIF_Logout_ResponseStruct() {
    }
}
