// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_getUserInfoByOUID_ResponseStruct {
    private com.skywin.webserviceclients.uip.QueryResult result;
    
    public UIPServiceIF_getUserInfoByOUID_ResponseStruct() {
    }
    
    public UIPServiceIF_getUserInfoByOUID_ResponseStruct(com.skywin.webserviceclients.uip.QueryResult result) {
        this.result = result;
    }
    
    public com.skywin.webserviceclients.uip.QueryResult getResult() {
        return result;
    }
    
    public void setResult(com.skywin.webserviceclients.uip.QueryResult result) {
        this.result = result;
    }
}
