// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_getUserInfoByUserID_RequestStruct {
    private java.lang.String string_1;
    private java.lang.String string_2;
    private java.lang.String string_3;
    
    public UIPServiceIF_getUserInfoByUserID_RequestStruct() {
    }
    
    public UIPServiceIF_getUserInfoByUserID_RequestStruct(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3) {
        this.string_1 = string_1;
        this.string_2 = string_2;
        this.string_3 = string_3;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_2() {
        return string_2;
    }
    
    public void setString_2(java.lang.String string_2) {
        this.string_2 = string_2;
    }
    
    public java.lang.String getString_3() {
        return string_3;
    }
    
    public void setString_3(java.lang.String string_3) {
        this.string_3 = string_3;
    }
}
