// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_getUserInfoByUserID_ResponseStruct {
    private com.skywin.webserviceclients.uip.UserInfo result;
    
    public UIPServiceIF_getUserInfoByUserID_ResponseStruct() {
    }
    
    public UIPServiceIF_getUserInfoByUserID_ResponseStruct(com.skywin.webserviceclients.uip.UserInfo result) {
        this.result = result;
    }
    
    public com.skywin.webserviceclients.uip.UserInfo getResult() {
        return result;
    }
    
    public void setResult(com.skywin.webserviceclients.uip.UserInfo result) {
        this.result = result;
    }
}
