// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

public interface UIPServiceIF extends java.rmi.Remote {
    public com.skywin.webserviceclients.uip.AuthResult SSOLogin(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, int int_4) throws 
         java.rmi.RemoteException;
    public com.skywin.webserviceclients.uip.AuthResult commonLogin(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, int int_4) throws 
         java.rmi.RemoteException;
    public com.skywin.webserviceclients.uip.AuthResult validateToken(java.lang.String string_1, java.lang.String string_2) throws 
         java.rmi.RemoteException;
    public void logout(java.lang.String string_1) throws 
         java.rmi.RemoteException;
    public com.skywin.webserviceclients.uip.UserInfo getUserInfoByUserID(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3) throws 
         java.rmi.RemoteException;
    public com.skywin.webserviceclients.uip.OrganizationInfo getOrgnizationInfoByOUID(int int_1, boolean boolean_2, java.lang.String string_3, java.lang.String string_4) throws 
         java.rmi.RemoteException;
    public com.skywin.webserviceclients.uip.QueryResult getUserInfoByOUID(int int_1, boolean boolean_2, java.lang.String string_3, java.lang.String string_4) throws 
         java.rmi.RemoteException;
    public com.skywin.webserviceclients.uip.AppResult applicationToDo(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, java.lang.String string_4, java.lang.String string_5, int int_6, java.lang.String string_7, java.lang.String string_8, java.lang.String string_9, java.lang.String string_10, int int_11) throws 
         java.rmi.RemoteException;
    public com.skywin.webserviceclients.uip.AppResult applicationToRead(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, java.lang.String string_4, int int_5, java.lang.String string_6, java.lang.String string_7, java.lang.String string_8, java.lang.String string_9, int int_10) throws 
         java.rmi.RemoteException;
    public java.lang.String getVersion() throws 
         java.rmi.RemoteException;
}
