// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_applicationToDo_ResponseStruct {
    private com.skywin.webserviceclients.uip.AppResult result;
    
    public UIPServiceIF_applicationToDo_ResponseStruct() {
    }
    
    public UIPServiceIF_applicationToDo_ResponseStruct(com.skywin.webserviceclients.uip.AppResult result) {
        this.result = result;
    }
    
    public com.skywin.webserviceclients.uip.AppResult getResult() {
        return result;
    }
    
    public void setResult(com.skywin.webserviceclients.uip.AppResult result) {
        this.result = result;
    }
}
