// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct {
    private int int_1;
    private boolean boolean_2;
    private java.lang.String string_3;
    private java.lang.String string_4;
    
    public UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct() {
    }
    
    public UIPServiceIF_getOrgnizationInfoByOUID_RequestStruct(int int_1, boolean boolean_2, java.lang.String string_3, java.lang.String string_4) {
        this.int_1 = int_1;
        this.boolean_2 = boolean_2;
        this.string_3 = string_3;
        this.string_4 = string_4;
    }
    
    public int getInt_1() {
        return int_1;
    }
    
    public void setInt_1(int int_1) {
        this.int_1 = int_1;
    }
    
    public boolean isBoolean_2() {
        return boolean_2;
    }
    
    public void setBoolean_2(boolean boolean_2) {
        this.boolean_2 = boolean_2;
    }
    
    public java.lang.String getString_3() {
        return string_3;
    }
    
    public void setString_3(java.lang.String string_3) {
        this.string_3 = string_3;
    }
    
    public java.lang.String getString_4() {
        return string_4;
    }
    
    public void setString_4(java.lang.String string_4) {
        this.string_4 = string_4;
    }
}
