// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_getOrgnizationInfoByOUID_ResponseStruct {
    private com.skywin.webserviceclients.uip.OrganizationInfo result;
    
    public UIPServiceIF_getOrgnizationInfoByOUID_ResponseStruct() {
    }
    
    public UIPServiceIF_getOrgnizationInfoByOUID_ResponseStruct(com.skywin.webserviceclients.uip.OrganizationInfo result) {
        this.result = result;
    }
    
    public com.skywin.webserviceclients.uip.OrganizationInfo getResult() {
        return result;
    }
    
    public void setResult(com.skywin.webserviceclients.uip.OrganizationInfo result) {
        this.result = result;
    }
}
