// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import javax.xml.rpc.*;

public interface UIPService extends javax.xml.rpc.Service {
    public com.skywin.webserviceclients.uip.UIPServiceIF getUIPServiceIFPort();
}
