// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_Logout_RequestStruct {
    private java.lang.String string_1;
    
    public UIPServiceIF_Logout_RequestStruct() {
    }
    
    public UIPServiceIF_Logout_RequestStruct(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
}
