// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UIPServiceIF_getVersion_ResponseStruct {
    private java.lang.String result;
    
    public UIPServiceIF_getVersion_ResponseStruct() {
    }
    
    public UIPServiceIF_getVersion_ResponseStruct(java.lang.String result) {
        this.result = result;
    }
    
    public java.lang.String getResult() {
        return result;
    }
    
    public void setResult(java.lang.String result) {
        this.result = result;
    }
}
