// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;

import com.sun.xml.rpc.encoding.SOAPInstanceBuilder;

public class UserInfo_SOAPBuilder implements SOAPInstanceBuilder {
    private UserInfo _instance;
    private java.lang.String userDN;
    private java.lang.String cmccaccount;
    private java.lang.String ext7;
    private java.lang.String ext1;
    private java.lang.String jobTitle;
    private java.lang.Integer ouid;
    private java.lang.String region;
    private java.lang.String address;
    private java.lang.String firstName;
    private java.lang.String department;
    private java.lang.String company;
    private java.lang.String ext9;
    private java.lang.String mobilePhone;
    private java.lang.String employeeNum;
    private java.lang.String branch;
    private java.lang.String ext6;
    private java.lang.String[] roleList;
    private java.lang.String ext8;
    private java.lang.String branchid;
    private java.lang.String workPhone;
    private java.lang.String ext4;
    private java.lang.String groupid;
    private java.lang.String group;
    private java.lang.String uid;
    private java.lang.String orderid;
    private java.lang.String ext3;
    private java.lang.String lastName;
    private java.lang.String ext2;
    private java.lang.String departmentid;
    private java.lang.String companyid;
    private java.lang.String ext5;
    private java.lang.String ext10;
    private java.lang.String fullName;
    private java.lang.String email;
    private static final int myUSERDN_INDEX = 0;
    private static final int myCMCCACCOUNT_INDEX = 1;
    private static final int myEXT7_INDEX = 2;
    private static final int myEXT1_INDEX = 3;
    private static final int myJOBTITLE_INDEX = 4;
    private static final int myOUID_INDEX = 5;
    private static final int myREGION_INDEX = 6;
    private static final int myADDRESS_INDEX = 7;
    private static final int myFIRSTNAME_INDEX = 8;
    private static final int myDEPARTMENT_INDEX = 9;
    private static final int myCOMPANY_INDEX = 10;
    private static final int myEXT9_INDEX = 11;
    private static final int myMOBILEPHONE_INDEX = 12;
    private static final int myEMPLOYEENUM_INDEX = 13;
    private static final int myBRANCH_INDEX = 14;
    private static final int myEXT6_INDEX = 15;
    private static final int myROLELIST_INDEX = 16;
    private static final int myEXT8_INDEX = 17;
    private static final int myBRANCHID_INDEX = 18;
    private static final int myWORKPHONE_INDEX = 19;
    private static final int myEXT4_INDEX = 20;
    private static final int myGROUPID_INDEX = 21;
    private static final int myGROUP_INDEX = 22;
    private static final int myUID_INDEX = 23;
    private static final int myORDERID_INDEX = 24;
    private static final int myEXT3_INDEX = 25;
    private static final int myLASTNAME_INDEX = 26;
    private static final int myEXT2_INDEX = 27;
    private static final int myDEPARTMENTID_INDEX = 28;
    private static final int myCOMPANYID_INDEX = 29;
    private static final int myEXT5_INDEX = 30;
    private static final int myEXT10_INDEX = 31;
    private static final int myFULLNAME_INDEX = 32;
    private static final int myEMAIL_INDEX = 33;
    
    public UserInfo_SOAPBuilder() {
    }
    
    public void setUserDN(java.lang.String userDN) {
        this.userDN = userDN;
    }
    
    public void setCmccaccount(java.lang.String cmccaccount) {
        this.cmccaccount = cmccaccount;
    }
    
    public void setExt7(java.lang.String ext7) {
        this.ext7 = ext7;
    }
    
    public void setExt1(java.lang.String ext1) {
        this.ext1 = ext1;
    }
    
    public void setJobTitle(java.lang.String jobTitle) {
        this.jobTitle = jobTitle;
    }
    
    public void setOuid(java.lang.Integer ouid) {
        this.ouid = ouid;
    }
    
    public void setRegion(java.lang.String region) {
        this.region = region;
    }
    
    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public void setDepartment(java.lang.String department) {
        this.department = department;
    }
    
    public void setCompany(java.lang.String company) {
        this.company = company;
    }
    
    public void setExt9(java.lang.String ext9) {
        this.ext9 = ext9;
    }
    
    public void setMobilePhone(java.lang.String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    
    public void setEmployeeNum(java.lang.String employeeNum) {
        this.employeeNum = employeeNum;
    }
    
    public void setBranch(java.lang.String branch) {
        this.branch = branch;
    }
    
    public void setExt6(java.lang.String ext6) {
        this.ext6 = ext6;
    }
    
    public void setRoleList(java.lang.String[] roleList) {
        this.roleList = roleList;
    }
    
    public void setExt8(java.lang.String ext8) {
        this.ext8 = ext8;
    }
    
    public void setBranchid(java.lang.String branchid) {
        this.branchid = branchid;
    }
    
    public void setWorkPhone(java.lang.String workPhone) {
        this.workPhone = workPhone;
    }
    
    public void setExt4(java.lang.String ext4) {
        this.ext4 = ext4;
    }
    
    public void setGroupid(java.lang.String groupid) {
        this.groupid = groupid;
    }
    
    public void setGroup(java.lang.String group) {
        this.group = group;
    }
    
    public void setUid(java.lang.String uid) {
        this.uid = uid;
    }
    
    public void setOrderid(java.lang.String orderid) {
        this.orderid = orderid;
    }
    
    public void setExt3(java.lang.String ext3) {
        this.ext3 = ext3;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public void setExt2(java.lang.String ext2) {
        this.ext2 = ext2;
    }
    
    public void setDepartmentid(java.lang.String departmentid) {
        this.departmentid = departmentid;
    }
    
    public void setCompanyid(java.lang.String companyid) {
        this.companyid = companyid;
    }
    
    public void setExt5(java.lang.String ext5) {
        this.ext5 = ext5;
    }
    
    public void setExt10(java.lang.String ext10) {
        this.ext10 = ext10;
    }
    
    public void setFullName(java.lang.String fullName) {
        this.fullName = fullName;
    }
    
    public void setEmail(java.lang.String email) {
        this.email = email;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myUSERDN_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCMCCACCOUNT_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT7_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT1_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myJOBTITLE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myOUID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myREGION_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myADDRESS_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myFIRSTNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myDEPARTMENT_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCOMPANY_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT9_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myMOBILEPHONE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEMPLOYEENUM_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myBRANCH_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT6_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myROLELIST_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT8_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myBRANCHID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myWORKPHONE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT4_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myGROUPID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myGROUP_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myUID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myORDERID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT3_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myLASTNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT2_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myDEPARTMENTID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCOMPANYID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT5_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEXT10_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myFULLNAME_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myEMAIL_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, Object memberValue) {
        switch(index) {
            case myUSERDN_INDEX:
                _instance.setUserDN((java.lang.String)memberValue);
                break;
            case myCMCCACCOUNT_INDEX:
                _instance.setCmccaccount((java.lang.String)memberValue);
                break;
            case myEXT7_INDEX:
                _instance.setExt7((java.lang.String)memberValue);
                break;
            case myEXT1_INDEX:
                _instance.setExt1((java.lang.String)memberValue);
                break;
            case myJOBTITLE_INDEX:
                _instance.setJobTitle((java.lang.String)memberValue);
                break;
            case myOUID_INDEX:
                _instance.setOuid((java.lang.Integer)memberValue);
                break;
            case myREGION_INDEX:
                _instance.setRegion((java.lang.String)memberValue);
                break;
            case myADDRESS_INDEX:
                _instance.setAddress((java.lang.String)memberValue);
                break;
            case myFIRSTNAME_INDEX:
                _instance.setFirstName((java.lang.String)memberValue);
                break;
            case myDEPARTMENT_INDEX:
                _instance.setDepartment((java.lang.String)memberValue);
                break;
            case myCOMPANY_INDEX:
                _instance.setCompany((java.lang.String)memberValue);
                break;
            case myEXT9_INDEX:
                _instance.setExt9((java.lang.String)memberValue);
                break;
            case myMOBILEPHONE_INDEX:
                _instance.setMobilePhone((java.lang.String)memberValue);
                break;
            case myEMPLOYEENUM_INDEX:
                _instance.setEmployeeNum((java.lang.String)memberValue);
                break;
            case myBRANCH_INDEX:
                _instance.setBranch((java.lang.String)memberValue);
                break;
            case myEXT6_INDEX:
                _instance.setExt6((java.lang.String)memberValue);
                break;
            case myROLELIST_INDEX:
                _instance.setRoleList((java.lang.String[])memberValue);
                break;
            case myEXT8_INDEX:
                _instance.setExt8((java.lang.String)memberValue);
                break;
            case myBRANCHID_INDEX:
                _instance.setBranchid((java.lang.String)memberValue);
                break;
            case myWORKPHONE_INDEX:
                _instance.setWorkPhone((java.lang.String)memberValue);
                break;
            case myEXT4_INDEX:
                _instance.setExt4((java.lang.String)memberValue);
                break;
            case myGROUPID_INDEX:
                _instance.setGroupid((java.lang.String)memberValue);
                break;
            case myGROUP_INDEX:
                _instance.setGroup((java.lang.String)memberValue);
                break;
            case myUID_INDEX:
                _instance.setUid((java.lang.String)memberValue);
                break;
            case myORDERID_INDEX:
                _instance.setOrderid((java.lang.String)memberValue);
                break;
            case myEXT3_INDEX:
                _instance.setExt3((java.lang.String)memberValue);
                break;
            case myLASTNAME_INDEX:
                _instance.setLastName((java.lang.String)memberValue);
                break;
            case myEXT2_INDEX:
                _instance.setExt2((java.lang.String)memberValue);
                break;
            case myDEPARTMENTID_INDEX:
                _instance.setDepartmentid((java.lang.String)memberValue);
                break;
            case myCOMPANYID_INDEX:
                _instance.setCompanyid((java.lang.String)memberValue);
                break;
            case myEXT5_INDEX:
                _instance.setExt5((java.lang.String)memberValue);
                break;
            case myEXT10_INDEX:
                _instance.setExt10((java.lang.String)memberValue);
                break;
            case myFULLNAME_INDEX:
                _instance.setFullName((java.lang.String)memberValue);
                break;
            case myEMAIL_INDEX:
                _instance.setEmail((java.lang.String)memberValue);
                break;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(Object instance) {
        _instance = (UserInfo)instance;
    }
    
    public Object getInstance() {
        return _instance;
    }
}
