// Helper class generated by xrpcc, do not edit.
// Contents subject to change without notice.

package com.skywin.webserviceclients.uip;


public class UserInfo {
    private java.lang.String userDN;
    private java.lang.String cmccaccount;
    private java.lang.String ext7;
    private java.lang.String ext1;
    private java.lang.String jobTitle;
    private java.lang.Integer ouid;
    private java.lang.String region;
    private java.lang.String address;
    private java.lang.String firstName;
    private java.lang.String department;
    private java.lang.String company;
    private java.lang.String ext9;
    private java.lang.String mobilePhone;
    private java.lang.String employeeNum;
    private java.lang.String branch;
    private java.lang.String ext6;
    private java.lang.String[] roleList;
    private java.lang.String ext8;
    private java.lang.String branchid;
    private java.lang.String workPhone;
    private java.lang.String ext4;
    private java.lang.String groupid;
    private java.lang.String group;
    private java.lang.String uid;
    private java.lang.String orderid;
    private java.lang.String ext3;
    private java.lang.String lastName;
    private java.lang.String ext2;
    private java.lang.String departmentid;
    private java.lang.String companyid;
    private java.lang.String ext5;
    private java.lang.String ext10;
    private java.lang.String fullName;
    private java.lang.String email;
    
    public UserInfo() {
    }
    
    public UserInfo(java.lang.String userDN, java.lang.String cmccaccount, java.lang.String ext7, java.lang.String ext1, java.lang.String jobTitle, java.lang.Integer ouid, java.lang.String region, java.lang.String address, java.lang.String firstName, java.lang.String department, java.lang.String company, java.lang.String ext9, java.lang.String mobilePhone, java.lang.String employeeNum, java.lang.String branch, java.lang.String ext6, java.lang.String[] roleList, java.lang.String ext8, java.lang.String branchid, java.lang.String workPhone, java.lang.String ext4, java.lang.String groupid, java.lang.String group, java.lang.String uid, java.lang.String orderid, java.lang.String ext3, java.lang.String lastName, java.lang.String ext2, java.lang.String departmentid, java.lang.String companyid, java.lang.String ext5, java.lang.String ext10, java.lang.String fullName, java.lang.String email) {
        this.userDN = userDN;
        this.cmccaccount = cmccaccount;
        this.ext7 = ext7;
        this.ext1 = ext1;
        this.jobTitle = jobTitle;
        this.ouid = ouid;
        this.region = region;
        this.address = address;
        this.firstName = firstName;
        this.department = department;
        this.company = company;
        this.ext9 = ext9;
        this.mobilePhone = mobilePhone;
        this.employeeNum = employeeNum;
        this.branch = branch;
        this.ext6 = ext6;
        this.roleList = roleList;
        this.ext8 = ext8;
        this.branchid = branchid;
        this.workPhone = workPhone;
        this.ext4 = ext4;
        this.groupid = groupid;
        this.group = group;
        this.uid = uid;
        this.orderid = orderid;
        this.ext3 = ext3;
        this.lastName = lastName;
        this.ext2 = ext2;
        this.departmentid = departmentid;
        this.companyid = companyid;
        this.ext5 = ext5;
        this.ext10 = ext10;
        this.fullName = fullName;
        this.email = email;
    }
    
    public java.lang.String getUserDN() {
        return userDN;
    }
    
    public void setUserDN(java.lang.String userDN) {
        this.userDN = userDN;
    }
    
    public java.lang.String getCmccaccount() {
        return cmccaccount;
    }
    
    public void setCmccaccount(java.lang.String cmccaccount) {
        this.cmccaccount = cmccaccount;
    }
    
    public java.lang.String getExt7() {
        return ext7;
    }
    
    public void setExt7(java.lang.String ext7) {
        this.ext7 = ext7;
    }
    
    public java.lang.String getExt1() {
        return ext1;
    }
    
    public void setExt1(java.lang.String ext1) {
        this.ext1 = ext1;
    }
    
    public java.lang.String getJobTitle() {
        return jobTitle;
    }
    
    public void setJobTitle(java.lang.String jobTitle) {
        this.jobTitle = jobTitle;
    }
    
    public java.lang.Integer getOuid() {
        return ouid;
    }
    
    public void setOuid(java.lang.Integer ouid) {
        this.ouid = ouid;
    }
    
    public java.lang.String getRegion() {
        return region;
    }
    
    public void setRegion(java.lang.String region) {
        this.region = region;
    }
    
    public java.lang.String getAddress() {
        return address;
    }
    
    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public java.lang.String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public java.lang.String getDepartment() {
        return department;
    }
    
    public void setDepartment(java.lang.String department) {
        this.department = department;
    }
    
    public java.lang.String getCompany() {
        return company;
    }
    
    public void setCompany(java.lang.String company) {
        this.company = company;
    }
    
    public java.lang.String getExt9() {
        return ext9;
    }
    
    public void setExt9(java.lang.String ext9) {
        this.ext9 = ext9;
    }
    
    public java.lang.String getMobilePhone() {
        return mobilePhone;
    }
    
    public void setMobilePhone(java.lang.String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    
    public java.lang.String getEmployeeNum() {
        return employeeNum;
    }
    
    public void setEmployeeNum(java.lang.String employeeNum) {
        this.employeeNum = employeeNum;
    }
    
    public java.lang.String getBranch() {
        return branch;
    }
    
    public void setBranch(java.lang.String branch) {
        this.branch = branch;
    }
    
    public java.lang.String getExt6() {
        return ext6;
    }
    
    public void setExt6(java.lang.String ext6) {
        this.ext6 = ext6;
    }
    
    public java.lang.String[] getRoleList() {
        return roleList;
    }
    
    public void setRoleList(java.lang.String[] roleList) {
        this.roleList = roleList;
    }
    
    public java.lang.String getExt8() {
        return ext8;
    }
    
    public void setExt8(java.lang.String ext8) {
        this.ext8 = ext8;
    }
    
    public java.lang.String getBranchid() {
        return branchid;
    }
    
    public void setBranchid(java.lang.String branchid) {
        this.branchid = branchid;
    }
    
    public java.lang.String getWorkPhone() {
        return workPhone;
    }
    
    public void setWorkPhone(java.lang.String workPhone) {
        this.workPhone = workPhone;
    }
    
    public java.lang.String getExt4() {
        return ext4;
    }
    
    public void setExt4(java.lang.String ext4) {
        this.ext4 = ext4;
    }
    
    public java.lang.String getGroupid() {
        return groupid;
    }
    
    public void setGroupid(java.lang.String groupid) {
        this.groupid = groupid;
    }
    
    public java.lang.String getGroup() {
        return group;
    }
    
    public void setGroup(java.lang.String group) {
        this.group = group;
    }
    
    public java.lang.String getUid() {
        return uid;
    }
    
    public void setUid(java.lang.String uid) {
        this.uid = uid;
    }
    
    public java.lang.String getOrderid() {
        return orderid;
    }
    
    public void setOrderid(java.lang.String orderid) {
        this.orderid = orderid;
    }
    
    public java.lang.String getExt3() {
        return ext3;
    }
    
    public void setExt3(java.lang.String ext3) {
        this.ext3 = ext3;
    }
    
    public java.lang.String getLastName() {
        return lastName;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public java.lang.String getExt2() {
        return ext2;
    }
    
    public void setExt2(java.lang.String ext2) {
        this.ext2 = ext2;
    }
    
    public java.lang.String getDepartmentid() {
        return departmentid;
    }
    
    public void setDepartmentid(java.lang.String departmentid) {
        this.departmentid = departmentid;
    }
    
    public java.lang.String getCompanyid() {
        return companyid;
    }
    
    public void setCompanyid(java.lang.String companyid) {
        this.companyid = companyid;
    }
    
    public java.lang.String getExt5() {
        return ext5;
    }
    
    public void setExt5(java.lang.String ext5) {
        this.ext5 = ext5;
    }
    
    public java.lang.String getExt10() {
        return ext10;
    }
    
    public void setExt10(java.lang.String ext10) {
        this.ext10 = ext10;
    }
    
    public java.lang.String getFullName() {
        return fullName;
    }
    
    public void setFullName(java.lang.String fullName) {
        this.fullName = fullName;
    }
    
    public java.lang.String getEmail() {
        return email;
    }
    
    public void setEmail(java.lang.String email) {
        this.email = email;
    }
}
