package com.sunrise.boss.business.fee.billing.billinglog.persistent;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * IbWlBillinglog generated by MyEclipse - Hibernate Tools
 */

public class BillingLogVO implements java.io.Serializable {

	// Fields

	private long logid;

	private long validbillcyc;

	private String billingcon;

	private Date starttime;

	private Date endtime;

	private String billingphase;

	private String subphase;

	private long processcnt;

	private double processamt;

	private String opercode;

	private String failreason;

	private long status;

	private String batchnum;

	private String citycomp;

	// Constructors

	/** default constructor */
	public BillingLogVO() {
	}

	/** minimal constructor */
	public BillingLogVO(long logid, long validbillcyc, String billingcon,
			String billingphase) {
		this.logid = logid;
		this.validbillcyc = validbillcyc;
		this.billingcon = billingcon;
		this.billingphase = billingphase;
	}

	/** full constructor */
	public BillingLogVO(long logid, long validbillcyc, String billingcon,
			Date starttime, Date endtime, String billingphase, String subphase,
			long processcnt, double processamt, String opercode,
			String failreason, long status, String batchnum, String citycomp) {
		this.logid = logid;
		this.validbillcyc = validbillcyc;
		this.billingcon = billingcon;
		this.starttime = starttime;
		this.endtime = endtime;
		this.billingphase = billingphase;
		this.subphase = subphase;
		this.processcnt = processcnt;
		this.processamt = processamt;
		this.opercode = opercode;
		this.failreason = failreason;
		this.status = status;
		this.batchnum = batchnum;
		this.citycomp = citycomp;
	}

	// Property accessors

	public long getLogid() {
		return this.logid;
	}

	public void setLogid(long logid) {
		this.logid = logid;
	}

	public long getValidbillcyc() {
		return this.validbillcyc;
	}

	public void setValidbillcyc(long validbillcyc) {
		this.validbillcyc = validbillcyc;
	}

	public String getBillingcon() {
		return this.billingcon;
	}

	public void setBillingcon(String billingcon) {
		this.billingcon = billingcon;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getBillingphase() {
		return this.billingphase;
	}

	public void setBillingphase(String billingphase) {
		this.billingphase = billingphase;
	}

	public String getSubphase() {
		return this.subphase;
	}

	public void setSubphase(String subphase) {
		this.subphase = subphase;
	}

	public long getProcesscnt() {
		return this.processcnt;
	}

	public void setProcesscnt(long processcnt) {
		this.processcnt = processcnt;
	}

	public double getProcessamt() {
		return this.processamt;
	}

	public void setProcessamt(double processamt) {
		this.processamt = processamt;
	}

	public String getOpercode() {
		return this.opercode;
	}

	public void setOpercode(String opercode) {
		this.opercode = opercode;
	}

	public String getFailreason() {
		return this.failreason;
	}

	public void setFailreason(String failreason) {
		this.failreason = failreason;
	}

	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	public String getBatchnum() {
		return this.batchnum;
	}

	public void setBatchnum(String batchnum) {
		this.batchnum = batchnum;
	}

	public String getCitycomp() {
		return this.citycomp;
	}

	public void setCitycomp(String citycomp) {
		this.citycomp = citycomp;
	}

	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (!(other instanceof BillingLogVO))
			return false;
		BillingLogVO castOther = (BillingLogVO) other;
		return new EqualsBuilder()
				.append(this.getLogid(), castOther.getLogid()).isEquals();
	}

	public int hashCode() {
		return new HashCodeBuilder().append(getLogid()).toHashCode();
	}

}