<%@ page language="java" contentType="text/html;charset=GBK"%>
<%@ include file="/inc/head.inc" %>
<script type="text/javascript" src="<%= contextPath %>/js/pub/list.js"></script>

<script type="text/javascript" language="javascript">
    var msgNoSelected="<bean:message bundle="public" key="msgNoSelected"/>"
    var msgConfirmDelete="<bean:message bundle="public" key="msgConfirmDelete"/>"
</script>
