package net.gmcc.pboss.comswebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.8
 * 2012-06-20T09:14:02.456+08:00
 * Generated source version: 2.3.8
 * 
 */
@WebService(targetNamespace = "http://www.gmcc.net/pboss/COMSWebService/", name = "COMSWebServicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface COMSWebServicePort {

    /**
     * 新业务编码申请接口
     */
    @WebResult(name = "opncodeapplyrsp", targetNamespace = "http://www.gmcc.net/pboss/COMSWebService/", partName = "opncodeapplyrsp")
    @WebMethod(action = "http://www.gmcc.net/pboss/COMSWebService/opncodeapply")
    public Opncodeapplyrsp opncodeapply(
        @WebParam(partName = "opncodeapplyreq", name = "opncodeapplyreq", targetNamespace = "http://www.gmcc.net/pboss/COMSWebService/")
        Opncodeapplyreq opncodeapplyreq
    );
}
