
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.gmcc.pboss.comswebservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import net.gmcc.pboss.domain.business.ServiceDispatcher;

/**
 * This class was generated by Apache CXF 2.3.8
 * 2012-06-20T09:14:02.443+08:00
 * Generated source version: 2.3.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "COMSWebService",
                      portName = "COMSWebServiceSOAP",
                      targetNamespace = "http://www.gmcc.net/pboss/COMSWebService/",
                      //wsdlLocation = "file:wsdl/COMSWebService.wsdl",
                      wsdlLocation = "data/COMSWebService.wsdl",
                      endpointInterface = "net.gmcc.pboss.comswebservice.COMSWebServicePort")
                      
public class COMSWebServicePortImpl implements COMSWebServicePort {

    private static final Logger LOG = Logger.getLogger(COMSWebServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see net.gmcc.pboss.comswebservice.COMSWebServicePort#opncodeapply(net.gmcc.pboss.comswebservice.Opncodeapplyreq  opncodeapplyreq )*
     */
    public net.gmcc.pboss.comswebservice.Opncodeapplyrsp opncodeapply(Opncodeapplyreq opncodeapplyreq) { 
        //LOG.info("Executing operation opncodeapply");
        //System.out.println(opncodeapplyreq);
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.comswebservice.Opncodeapplyrsp _return = dispatcher.opncodeapply(opncodeapplyreq);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
