
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.gmcc.pboss.b2mservice;

import net.gmcc.pboss.domain.business.ServiceDispatcher;

/**
 * This class was generated by Apache CXF 2.3.8
 * 2014-01-02T14:13:57.617+08:00
 * Generated source version: 2.3.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "B2MService",
                      portName = "B2MServiceSoap",
                      targetNamespace = "http://www.gmcc.net/pboss/B2MService/",
                      wsdlLocation = "/data/B2MService.wsdl",
                      //wsdlLocation = "file:D:/workspace/PBOSS4CRM/src/data/B2MService.wsdl",
                      endpointInterface = "net.gmcc.pboss.b2mservice.B2MServicePort")
                      
public class B2MServicePortImpl implements B2MServicePort {

    /* (non-Javadoc)
     * @see net.gmcc.pboss.b2mservice.B2MServicePort#singlerecord(net.gmcc.pboss.b2mservice.Singlerecordrequest  request )*
     */
    public net.gmcc.pboss.b2mservice.Singlerecordresponse singlerecord(Singlerecordrequest request) { 
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.b2mservice.Singlerecordresponse _return = dispatcher.singlerecord(request);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.gmcc.pboss.b2mservice.B2MServicePort#monthstatistic(net.gmcc.pboss.b2mservice.Monthstatisticrequest  request )*
     */
    public net.gmcc.pboss.b2mservice.Monthstatisticresponse monthstatistic(Monthstatisticrequest request) { 
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.b2mservice.Monthstatisticresponse _return = dispatcher.monthstatistic(request);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.gmcc.pboss.b2mservice.B2MServicePort#sumstatistic(net.gmcc.pboss.b2mservice.Sumstatisticrequest  request )*
     */
    public net.gmcc.pboss.b2mservice.Sumstatisticresponse sumstatistic(Sumstatisticrequest request) { 
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.b2mservice.Sumstatisticresponse _return = dispatcher.sumstatistic(request);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.gmcc.pboss.b2mservice.B2MServicePort#monthdetail(net.gmcc.pboss.b2mservice.Monthdetailrequest  request )*
     */
    public net.gmcc.pboss.b2mservice.Monthdetailresponse monthdetail(Monthdetailrequest request) { 
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.b2mservice.Monthdetailresponse _return = dispatcher.monthdetail(request);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    /* (non-Javadoc)
     * @see net.gmcc.pboss.b2mservice.B2MServicePort#smsbosyn(net.gmcc.pboss.b2mservice.Smsbosynrequest  request )*
     */
    public net.gmcc.pboss.b2mservice.Smsbosynresponse smsbosyn(Smsbosynrequest request) { 
        try {
        	ServiceDispatcher dispatcher = new ServiceDispatcher();
            net.gmcc.pboss.b2mservice.Smsbosynresponse _return = dispatcher.smsbosyn(request);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
